query ShowAccessType($accessTypeId: Int!) {
  accessType(id: $accessTypeId) {
    id
    name
    description
    enter_and_exit_option
    price
    createdAt
    updatedAt
    deleted
    deletedAt
  }
}
