mutation CreateAccessType($data: CreateAccessTypeInput!) {
  createAccessType(data: $data) {
    id
    name
    description
    available_tickets_count
    enter_and_exit_option
    price
    createdAt
    updatedAt
  }
}
