query ShowRoleForEdit($roleId: Int!) {
  role(id: $roleId) {
    id
    name
    description
    createdAt
    updatedAt
    deletedAt
    abilities {
      id
      name
      description
    }
  }
  abilitys {
    id
    name
  }
}
