query RolesList($pagination: Pagination) {
  roles(pagination: $pagination) {
    pagination {
      take
      skip
      pages
      currentPage
      nextPage
    }
    count
    data {
      id
      name
      description
      abilities {
        id
        name
      }
      createdAt
      updatedAt
      deletedAt
    }
  }
}
