query ShowRole($roleId: Int!) {
  role(id: $roleId) {
    id
    name
    description
    createdAt
    updatedAt
    deletedAt
    abilities {
      id
      name
    }
    users {
      id
      name
      last_name
      email
      createdAt
      updatedAt
      roles {
        id
        name
      }
    }
  }
}
