query ShowOrganization($organizationId: Int!) {
  organization(id: $organizationId) {
    id
    name
    createdAt
    deleted
    deletedAt
    events {
      id
      name
      description
      event_location
      start_date
      end_date
    }
  }
}
