query ShowSelledByEvent($eventId: Int!) {
  event(id: $eventId) {
    id
    name
    description
    event_logo_url
    event_location
  }

  selled_tickets_by_event(event_id: $eventId) {
    id
    createdAt
    serial_number
    service_charge
    is_paid
    is_used
    note
    price
  }
}
