query MainSearch($query: String!) {
  search_events(query: $query) {
    id
    name
    description
    start_date
    price_from
    event_location
    event_logo {
      id
      url
    }
    event_sub_categories {
      id
      name
    }
  }
  searchOrganizations(query: $query) {
    id
    name
    current_events_count
  }
}
