mutation CreateEvent($input: CreateEventInput!) {
  createEvent(data: $input) {
    id
    event_key
    name
    description
    event_location
    start_date
    start_time
    end_time
    re_entry
    event_logo {
      id
      url
    }
    userId
    event_sub_categories {
      id
      name
    }
  }
}
