query LandingView {
  eventCategories {
    id
    name
  }

  popular_events {
    id
    name
    description
    start_date
    event_location
    event_logo {
      id
      url
    }
    event_banner {
      id
      url
    }
  }
}
