query SearchEventsBySubcategory($subCategoryId: Int!) {
  eventSubCategory(id: $subCategoryId) {
    id
    name
  }
  eventsBySubcategory(subCategoryId: $subCategoryId) {
    id
    event_key
    name
    event_location
    start_date
    start_time
    end_time
    price_from
    price_to
    event_logo {
      id
      url
    }
    event_banner {
      id
      url
    }
    organization {
      id
      name
    }
  }
}
