query ShowEvents {
  events {
    id
    event_logo_url
    event_location
    event_key
    name
    description
    start_date
    deleted
    event_banner_url
    event_sub_categories {
      id
      name
    }
  }
}
