query ShowEvents {
  events {
    id
    event_location
    event_key
    name
    description
    start_date
    deleted
    event_logo {
      id
      url
    }
    event_logo {
      id
      url
    }
    event_sub_categories {
      id
      name
    }
  }
}
