mutation UpdateEvent($updateEventId: Int!, $input: UpdateEventInput!) {
  updateEvent(id: $updateEventId, data: $input) {
    id
    event_key
    name
    description
    event_location
    start_date
    start_time
    end_time
    re_entry
    event_logo {
      id
      url
    }
    event_banner {
      id
      url
    }
    userId
    event_sub_categories {
      id
      name
    }
  }
}
