mutation UpdateEvent($updateEventId: Int!, $input: UpdateEventInput!) {
  updateEvent(id: $updateEventId, input: $input) {
    id
    event_key
    name
    description
    event_location
    event_logo_url
    date
    start_time
    end_time
    re_entry
    event_logo_url
    hostId
  }
}
