mutation UpdateEvent($updateEventId: Int!, $input: UpdateEventInput!) {
  updateEvent(id: $updateEventId, data: $input) {
    id
    event_key
    name
    description
    event_location
    event_logo_url
    start_date
    start_time
    end_time
    re_entry
    event_logo_url
    userId
    event_sub_categories {
      id
      name
    }
  }
}
