mutation CreateEventCategory($data: CreateEventCategoryInput!) {
  createEventCategory(data: $data) {
    id
    name
    description
    sub_categories {
      name
      description
    }
    createdAt
    updatedAt
  }
}
