query EventCategories {
  eventCategories {
    id
    name
    description
    event_sub_categories {
      id
      name
      event_categoryId
    }
  }

  eventSubCategories {
    id
    name
    event_categoryId
  }
}
