mutation ModifyEventCategory(
  $updateEventCategoryId: Int!
  $data: UpdateEventCategoryInput!
) {
  updateEventCategory(id: $updateEventCategoryId, data: $data) {
    id
    name
    description
    updatedAt
    createdAt
    event_sub_categories {
      id
      name
    }
  }
}
