query ShowEventCategory($eventCategoryId: Int!) {
  eventCategory(id: $eventCategoryId) {
    id
    name
    description
    events_count
    event_sub_categories_count
    events_count
    event_sub_categories {
      id
      name
      description
      createdAt
      updatedAt
    }
    createdAt
    updatedAt
  }
}
